name: full-check

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: sudo apt install libgd-dev libpng-dev zlib1g-dev
    - name: build_and_install
      run: |
           cd src
           ./bootstrap
           ./configure
           make
           make doc
           sudo make install
    - name: basic_test_mrtg
      run: |
           mkdir test-mrtg
           cd test-mrtg
           echo "WorkDir: $GITHUB_WORKSPACE/test-mrtg" > mrtg.cfg
           LANG=C /opt/mrtg-2/bin/mrtg mrtg.cfg
           ls
           ls | egrep mrtg-r.png
           ls | egrep mrtg.ok
